FROM mcr.microsoft.com/windows/servercore:ltsc2022
SHELL ["powershell", "-NoLogo", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN Invoke-WebRequest -Uri 'https://nodejs.org/dist/v22.14.0/node-v22.14.0-win-x64.zip' -OutFile C:\node.zip; Expand-Archive -Path C:\node.zip -DestinationPath C:\; Rename-Item 'C:\node-v22.14.0-win-x64' C:\nodejs; Remove-Item C:\node.zip
WORKDIR C:/app
COPY package*.json ./
RUN cmd.exe /c C:\nodejs\npm.cmd install --omit=dev
COPY app.js ./
EXPOSE 3000
CMD ["C:/nodejs/node.exe", "app.js"]